all: a6

a6: a6.o hash.h hash.o
	clang -std=c99 -Wall -pedantic a6.o hash.o -o a6

a6.o: a6.c hash.h
	clang -std=c99 -Wall -pedantic -c a6.c -o a6.o

hash.o: hash.c hash.h
	clang -std=c99 -Wall -pedantic -c hash.c -o hash.o

clean:
	rm *.o a6




